#!/bin/bash
# Generate build_info.dart with current git information
# Called by GitHub Actions before build

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

COMMIT_HASH=$(git rev-parse --short HEAD)
COMMIT_COUNT=$(git rev-list --count HEAD)
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$PROJECT_ROOT/lib/build_info.dart" << EOF
// GENERATED FILE - DO NOT EDIT
// Auto-generated by GitHub Actions

const String gitCommitHash = '$COMMIT_HASH';
const String gitCommitCount = '$COMMIT_COUNT';
const String buildTimestamp = '$BUILD_TIME';
EOF

echo "✓ Generated build_info.dart: #$COMMIT_COUNT ($COMMIT_HASH)"
