#!/bin/bash
# Generate build_info.dart with current git information
# Called by GitHub Actions before build

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

COMMIT_HASH=$(git rev-parse --short HEAD)
COMMIT_COUNT=$(git rev-list --count HEAD)
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Get branch name - works in GitHub Actions and locally
GIT_BRANCH=${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}

cat > "$PROJECT_ROOT/lib/build_info.dart" << EOF
// GENERATED FILE - DO NOT EDIT
// Auto-generated by GitHub Actions or generate_build_info.sh

const String gitCommitHash = '$COMMIT_HASH';
const String gitBranch = '$GIT_BRANCH';
const String gitCommitCount = '$COMMIT_COUNT';
const String buildTimestamp = '$BUILD_TIME';
EOF

echo "✓ Generated build_info.dart: $GIT_BRANCH #$COMMIT_COUNT ($COMMIT_HASH)"
